# Data Preprocessing - Delhi Traffic Dataset

In [3]:
import pandas as pd

# Load datasets
features_df = pd.read_csv("../data/raw/delhi_traffic_features.csv")
target_df = pd.read_csv("../data/raw/delhi_traffic_target.csv")

# Preview
features_df.head()

,Trip_ID,start_area,end_area,distance_km,time_of_day,day_of_week,weather_condition,traffic_density_level,road_type,average_speed_kmph
0,TRIP_00001,Vasant Kunj,Kalkaji,9.44,Night,Weekday,Clear,Low,Main Road,37.8
1,TRIP_00002,Greater Kailash,Kalkaji,2.15,Night,Weekend,Clear,Low,Main Road,42.7
2,TRIP_00003,Janakpuri,Model Town,14.54,Morning Peak,Weekday,Rain,High,Inner Road,9.7
3,TRIP_00004,Punjabi Bagh,Dwarka,11.86,Night,Weekday,Clear,Low,Highway,68.5
4,TRIP_00005,Rohini,Chandni Chowk,20.26,Afternoon,Weekday,Fog,Medium,Highway,30.3

In [4]:
target_df.head()

      Trip_ID  travel_time_minutes
0  TRIP_00001                 15.3
1  TRIP_00002                  3.0
2  TRIP_00003                 92.7
3  TRIP_00004                 10.6
4  TRIP_00005                 42.0

In [5]:
features_df.shape

(4000, 10)

In [6]:
features_df.columns

Index(['Trip_ID', 'start_area', 'end_area', 'distance_km', 'time_of_day',
       'day_of_week', 'weather_condition', 'traffic_density_level',
       'road_type', 'average_speed_kmph'],
      dtype='str')

In [7]:
features_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Trip_ID                4000 non-null   str
 1   start_area             4000 non-null   str
 2   end_area               4000 non-null   str
 3   distance_km            4000 non-null   float64
 4   time_of_day            4000 non-null   str
 5   day_of_week            4000 non-null   str
 6   weather_condition      4000 non-null   str
 7   traffic_density_level  4000 non-null   str
 8   road_type              4000 non-null   str
 9   average_speed_kmph     4000 non-null   float64
dtypes: float64(2), str(8)
memory usage: 312.6 KB

In [8]:
features_df.isnull().sum()

Trip_ID                  0
start_area               0
end_area                 0
distance_km              0
time_of_day              0
day_of_week              0
weather_condition        0
traffic_density_level    0
road_type                0
average_speed_kmph       0
dtype: int64

In [9]:
target_df.head()
target_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Trip_ID              4000 non-null   str
 1   travel_time_minutes  4000 non-null   float64
dtypes: float64(1), str(1)
memory usage: 62.6 KB

In [10]:
features_df.shape

(4000, 10)

In [11]:
# Shape (rows, columns)
print(features_df.shape)

# Column names
print(features_df.columns)

# Dataset info
features_df.info()

# Missing values
print(features_df.isnull().sum())

# Target dataset preview
print(target_df.head())

# Target dataset info
target_df.info()

(4000, 10)
Index(['Trip_ID', 'start_area', 'end_area', 'distance_km', 'time_of_day',
       'day_of_week', 'weather_condition', 'traffic_density_level',
       'road_type', 'average_speed_kmph'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Trip_ID                4000 non-null   str
 1   start_area             4000 non-null   str
 2   end_area               4000 non-null   str
 3   distance_km            4000 non-null   float64
 4   time_of_day            4000 non-null   str
 5   day_of_week            4000 non-null   str
 6   weather_condition      4000 non-null   str
 7   traffic_density_level  4000 non-null   str
 8   road_type              4000 non-null   str
 9   average_speed_kmph     4000 non-null   float64
dtypes: float64(2), str(8)
memory usage: 312.6 KB
Trip_ID                  0
start_area               0
end_area                 0
distance_km              0
time_of_day              0
day_of_week              0
weather_condition        0
traffic_density_level    0
road_type                0
average_speed_kmph       0
dtype: int64
      Trip_ID  travel_time_minutes
0  TRIP_00001                 15.3
1  TRIP_00002                  3.0
2  TRIP_00003                 92.7
3  TRIP_00004                 10.6
4  TRIP_00005                 42.0
<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Trip_ID              4000 non-null   str
 1   travel_time_minutes  4000 non-null   float64
dtypes: float64(1), str(1)
memory usage: 62.6 KB

In [12]:
# Check duplicate rows
features_df.duplicated().sum()

np.int64(0)

In [13]:
# Merge features and target data
traffic_df = pd.merge(features_df, target_df, on="Trip_ID")

# Preview merged dataset
traffic_df.head()

,Trip_ID,start_area,end_area,distance_km,time_of_day,day_of_week,weather_condition,traffic_density_level,road_type,average_speed_kmph,travel_time_minutes
0,TRIP_00001,Vasant Kunj,Kalkaji,9.44,Night,Weekday,Clear,Low,Main Road,37.8,15.3
1,TRIP_00002,Greater Kailash,Kalkaji,2.15,Night,Weekend,Clear,Low,Main Road,42.7,3.0
2,TRIP_00003,Janakpuri,Model Town,14.54,Morning Peak,Weekday,Rain,High,Inner Road,9.7,92.7
3,TRIP_00004,Punjabi Bagh,Dwarka,11.86,Night,Weekday,Clear,Low,Highway,68.5,10.6
4,TRIP_00005,Rohini,Chandni Chowk,20.26,Afternoon,Weekday,Fog,Medium,Highway,30.3,42.0

In [14]:
traffic_df.shape

(4000, 11)

In [15]:
traffic_df.columns

Index(['Trip_ID', 'start_area', 'end_area', 'distance_km', 'time_of_day',
       'day_of_week', 'weather_condition', 'traffic_density_level',
       'road_type', 'average_speed_kmph', 'travel_time_minutes'],
      dtype='str')

In [16]:
# Save cleaned/merged dataset
traffic_df.to_csv(
    "../data/cleaned/delhi_traffic_cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [17]:
# Load cleaned dataset to verify
cleaned_df = pd.read_csv("../data/cleaned/delhi_traffic_cleaned.csv")

cleaned_df.head()

,Trip_ID,start_area,end_area,distance_km,time_of_day,day_of_week,weather_condition,traffic_density_level,road_type,average_speed_kmph,travel_time_minutes
0,TRIP_00001,Vasant Kunj,Kalkaji,9.44,Night,Weekday,Clear,Low,Main Road,37.8,15.3
1,TRIP_00002,Greater Kailash,Kalkaji,2.15,Night,Weekend,Clear,Low,Main Road,42.7,3.0
2,TRIP_00003,Janakpuri,Model Town,14.54,Morning Peak,Weekday,Rain,High,Inner Road,9.7,92.7
3,TRIP_00004,Punjabi Bagh,Dwarka,11.86,Night,Weekday,Clear,Low,Highway,68.5,10.6
4,TRIP_00005,Rohini,Chandni Chowk,20.26,Afternoon,Weekday,Fog,Medium,Highway,30.3,42.0